apiVersion: apps/v1 # aqui define a versão da API do Kubernetes que estamos usando para criar o Deployment baseado no k8s instalado no cluster
kind: Deployment # tipo do recursos a ser criado, no caso um Deployment
metadata: # info para o kubernetes identificar o recurso
  name: alvo-demo # nome do recurso
  namespace: default # namespace onde o recurso será criado
spec: # especificações do recurso no o recurso é o Deployment
  replicas: 1 # número de réplicas do pod que o Deployment deve manter e é gerenciado pelo replicaset
  selector:
    matchLabels:
      etiqueta: alvo-demo # rótulo usado para selecionar os pods que o Deployment irá gerenciar, deve ser igual ao rótulo definido no template
  template: # define o modelo do pod - tudo que tiver dentro desse escopo/alinhamento definira o pod e os containers
    metadata:
      labels: # rótulos aplicados ao pod criado pelo Deployment deve bater com o seletor acima
        etiqueta: alvo-demo
    spec:
      containers:
        - name: banana
          image: nginx:1.27-alpine # imagem do container, nesse caso é a imagem do nginx na versão 1.27-alpine 10.3.228.38 ip-10-3-236-226.ec2.internal/10.3.236.226
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi" # 1000Mi = 1 GiB
              cpu: "250m" # 1 vCPU quebra em 1000 10m = 0.01 vCPU
            limits:
              memory: "128Mi"
              cpu: "500m"
        - name: sidecar
          image: busybox:1.36
          command: ["sh", "-c", "while true; do sleep 3600; done"]
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "200m"
           